// USER ACTIONS
export const AUTH_USER = 'AUTH_USER';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

export const CHECK_USER_LOGGED_IN = 'CHECK_USER_LOGGED_IN';
export const USER_LOGOUT = 'USER_LOGOUT';

// MODE ACTIONS
export const SET_MODE = 'SET_MODE';

// CONSUMER ACTIONS
export const FETCH_CONSUMERS = 'FETCH_CONSUMERS';
export const SET_CURRENT_CONSUMER = 'SET_CURRENT_CONSUMER';

// API ACTIONS
export const FETCH_APIS = 'FETCH_APIS';
export const SET_CURRENT_API = 'SET_CURRENT_API'

// MISC
export const AJAX_ERROR = 'AJAX_ERROR';
export const RESET_STATE = 'RESET_STATE';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
